### ISSUE TITLE
How to run sentence transformers ONNX in Noide js? 

### ISSUE THREAD

**Issue by DoctorSlimm** [davidberenstein1957/fast-sentence-transformers#10]
Minimum working example for all-MiniLM-L6 pls 🙏

Including the tokenizer*****

**Comment by davidberenstein1957** [comment]
Hi @DoctorSlimm, sadly this isn't possible with this package. You should be able to run the exported ONNX representation of the package thought.

**Comment by davidberenstein1957** [comment]
https://github.com/microsoft/onnxjs
