### ISSUE TITLE
Why is the original model required?

### ISSUE THREAD

**Issue by mgoldenbe** [davidberenstein1957/fast-sentence-transformers#14]
I tried removing the original files from .cache and leaving only the .onnx file. However, when I ran the script it downloaded the original model again. How can I get rid of the dependency on the original model? In fact, given onnx, I should only need onnxruntime to make inferences. So, how do I get rid of the dependencies such as torch?

**Comment by Sayed-Ameer** [comment]
did you find a solution, for the whole model dependency?

**Comment by antonmosin** [comment]
The answer is in this line https://github.com/davidberenstein1957/fast-sentence-transformers/blob/main/fast_sentence_transformers/FastSentenceTransformer.py#L189

This package not only converts the model to onnx format, but also instantiates it to run the inference. To run the inference, you need the tokenizer, which is expected in the `cache_folder`

**Comment by davidberenstein1957** [comment]
Sorry for the late response but I've got good news! Sentence Transformers has an awesome maintainer again @tomaarsen, along with awesome ONNX integration, therefore I decided to archive this project. https://github.com/UKPLab/sentence-transformers
