### ISSUE TITLE
max length setting

### ISSUE THREAD

**Issue by DeoLeung** [davidberenstein1957/fast-sentence-transformers#15]
https://github.com/davidberenstein1957/fast-sentence-transformers/blob/main/fast_sentence_transformers/FastSentenceTransformer.py#L330

hi, I just wonder should this `512` be set from `config.json`'s `max_position_embeddings`?

**Comment by davidberenstein1957** [comment]
Sorry for the late response but I've got good news! Sentence Transformers has an awesome maintainer again @tomaarsen, along with awesome ONNX integration, therefore I decided to archive this project. https://github.com/UKPLab/sentence-transformers
