### ISSUE TITLE
Version conflict with onnxruntime

### ISSUE THREAD

**Issue by remydeshayes** [davidberenstein1957/fast-sentence-transformers#16]
Hi 👋

Installed latest version of `fast-sentence-transformers` through pip on a fresh environment running `python 3-10`.

`model = SentenceTransformer("all-MiniLM-L6-v2", device='cpu', quantize=True)` returned `quantize_dynamic() got an unexpected keyword argument 'optimize_model'`.

This argument was removed by microsoft in June 2023 in this commit [url](https://github.com/microsoft/onnxruntime/commit/89f8f20a61ceac0276c42d894c38400d86b175d0) which was then part of `onnxruntime` release `1.16.0` 

Probable causes of bug:
It seems that the install is now bringing `onnx 1.15` and `onnxruntime 1.16.1`as a dependency which causes the error above.

**Comment by davidberenstein1957** [comment]
Sorry for the late response but I've got good news! Sentence Transformers has an awesome maintainer again @tomaarsen, along with awesome ONNX integration, therefore I decided to archive this project. https://github.com/UKPLab/sentence-transformers
